apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-matchmaking-notification-service
spec:
  selector:
    matchLabels:
      app: sport-matchmaking-notification-service
  template:
    metadata:
      labels:
        app: sport-matchmaking-notification-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: sport-matchmaking-notification-service
        image: sport-matchmaking-notification-service:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: "16Mi"
            ephemeral-storage: "64Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 8080
        env:
          - name: MATCH_SERVICE_URL
            value: "http://sport-matchmaking-match-service-service:8080"
          - name: MATCH_SERVICE_CLIENT_API_KEY
            valueFrom:
              secretKeyRef:
                name: notification-service-match-service-secret
                key: apiKey
          - name: KEYCLOAK_URL
            valueFrom:
              secretKeyRef:
                name: notification-service-keycloak-credentials
                key: url
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: notification-service-keycloak-credentials
                key: realm
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: notification-service-keycloak-credentials
                key: clientId
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: notification-service-keycloak-credentials
                key: clientSecret
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: notification-service-smtp-credentials
                key: host
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: notification-service-smtp-credentials
                key: username
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notification-service-smtp-credentials
                key: password